import type { ExplorerState } from '../ExplorerState/ExplorerState.ts'

export const createDefaultState = (): ExplorerState => ({
  uid: 1,
  parentUid: 0,
  root: '/',
  items: [],
  focusedIndex: 0,
  focused: true,
  hoverIndex: 0,
  x: 0,
  y: 0,
  width: 100,
  height: 100,
  deltaY: 0,
  minLineY: 0,
  maxLineY: 0,
  pathSeparator: '/',
  version: 1,
  editingIndex: 0,
  itemHeight: 20,
  dropTargets: [],
  excluded: [],
  editingValue: '',
  editingType: 0,
  editingIcon: '',
  editingErrorMessage: '',
  icons: [],
  useChevrons: false,
  confirmDelete: true,
  fileIconCache: {},
  platform: 0,
  focus: 0,
  inputSource: 0,
  editingSelectionEnd: 0,
  editingSelectionStart: 0,
  focusWord: '',
  focusWordTimeout: 1000,
  finalDeltaY: 0,
  handleOffset: 0,
  scrollBarActive: false,
  scrollBarHeight: 0,
})
