export const HandleClick = 'handleClick'
export const HandleClickOpenFolder = 'handleClickOpenFolder'
export const HandleContextMenu = 'handleContextMenu'
export const HandleEditingInput = 'handleEditingInput'
export const HandleListBlur = 'handleListBlur'
export const HandleListFocus = 'handleListFocus'
export const HandlePointerDown = 'handlePointerDown'
export const HandleWheel = 'handleWheel'
