export const HandleBlur = 'handleBlur'
export const HandleClick = 'handleClick'
export const HandleClickOpenFolder = 'handleClickOpenFolder'
export const HandleContextMenu = 'handleContextMenu'
export const HandleEditingInput = 'handleEditingInput'
export const HandleFocus = 'handleFocus'
export const HandlePointerDown = 'handlePointerDown'
export const HandleWheel = 'handleWheel'
