export const HandleBlur = 'handleBlur'
export const HandleClick = 'handleClick'
export const handleClickOpenFolder = 'handleClickOpenFolder'
export const HandleContextMenu = 'handleContextMenu'
export const HandleFocus = 'handleFocus'
export const HandlePointerDown = 'handlePointerDown'
export const HandleWheel = 'handleWheel'
