name: Flaky E2E

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    if: github.event.pull_request.draft
    name: e2e (windows-2025, iteration ${{ matrix.iteration }})
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        iteration: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    runs-on: windows-2025
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Compute node modules cache key
        id: nodeModulesCacheKey
        run: echo "value=$(node packages/build/src/computeNodeModulesCacheKey.ts)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v6
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cacheNodeModules-${{ steps.nodeModulesCacheKey.outputs.value }}
      - name: npm ci
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm run build
      - run: npm run build:static
      - name: install playwright system dependencies
        working-directory: ./packages/e2e
        if: runner.os == 'Linux'
        run: sudo npx playwright install-deps firefox
      - name: install playwright dependencies
        working-directory: ./packages/e2e
        run: npx playwright install firefox
        if: steps.npm-cache.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: Add test progress diagnostics
        working-directory: ./packages/e2e
        run: node ./scripts/patch-e2e-progress-logging.js
      - name: Run Firefox e2e suite
        working-directory: ./packages/e2e
        shell: bash
        run: |
          npm run e2e:firefox:headless -- --timeout=900000 2>&1 | tee firefox-e2e.log
          exit ${PIPESTATUS[0]}
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: Upload e2e logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: e2e-logs-windows-2025-${{ matrix.iteration }}
          path: |
            packages/e2e/firefox-e2e.log
